/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author VICTOR
 */
public class NewConsultasE extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewConsultasE
     */
    public NewConsultasE() {
        initComponents();
        limpiar();
        bloquear();
    }

    void cargar(String valor) {

        //PARA CONSULTAS
        String codcli = "", codtec = "";
        String sql = "SELECT * FROM consultas WHERE CONCAT(cod_con) LIKE '%" + valor + "%'";
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        Statement st;
        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();

            txtcodcon.setText(rs.getString("cod_con"));
            txtfecini.setText(rs.getString("fec_rev"));
            txtfecter.setText(rs.getString("fec_ter"));
            txtpro.setText(rs.getString("pro_con"));
            txtsol.setText(rs.getString("sol_con"));
            txtcodcli.setText(rs.getString("cliente_cod_cli"));
            txtcodtec.setText(rs.getString("tecnico_cod_tec"));
            codcli = rs.getString("cliente_cod_cli");
            codtec = rs.getString("tecnico_cod_tec");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        //PARA CLIENTES
        sql = "SELECT * FROM clientes WHERE CONCAT(cod_cli) LIKE '%" + codcli + "%'";
        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();

            txtnomcli.setText(rs.getString("nom_cli"));
            txtapecli.setText(rs.getString("ape_cli"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        //PARA TECNICOS
        sql = "SELECT * FROM tecnicos WHERE CONCAT(cod_tec) LIKE '%" + codtec + "%'";
        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();

            txtnomtec.setText(rs.getString("nom_tec"));
            txtaptec.setText(rs.getString("ape_tec"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    void limpiar() {
        txtcodcon.setText("");
        txtnomcli.setText("");
        txtnomtec.setText("");
        txtapecli.setText("");
        txtaptec.setText("");
        txtfecini.setText("");
        txtpro.setText("");
        txtsol.setText("");
        txtfecter.setText("");
        txtcodcli.setText("");
        txtcodtec.setText("");
        txtBus.setText("");
    }

    void bloquear() {
        txtcodcon.setEnabled(false);
        txtnomcli.setEnabled(false);
        txtnomtec.setEnabled(false);
        txtapecli.setEnabled(false);
        txtaptec.setEnabled(false);
        txtfecini.setEnabled(false);
        txtpro.setEnabled(false);
        txtsol.setEnabled(false);
        txtfecter.setEnabled(false);
        txtcodcli.setEnabled(false);
        txtcodtec.setEnabled(false);
        txtBus.setEnabled(true);
        btnAct.setEnabled(false);

    }

    void desbloquear() {
        txtcodcon.setEnabled(false);
        txtnomcli.setEnabled(false);
        txtnomtec.setEnabled(false);
        txtapecli.setEnabled(false);
        txtaptec.setEnabled(false);
        txtfecini.setEnabled(true);
        txtpro.setEnabled(true);
        txtsol.setEnabled(true);
        txtfecter.setEnabled(true);
        txtcodcli.setEnabled(true);
        txtcodtec.setEnabled(true);
        txtBus.setEnabled(true);
        btnAct.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtBus = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtcodcon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtnomcli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnomtec = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfecini = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpro = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtsol = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        txtfecter = new javax.swing.JTextField();
        btnAct = new javax.swing.JButton();
        txtaptec = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtapecli = new javax.swing.JTextField();
        btnEdi = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtcodcli = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtcodtec = new javax.swing.JTextField();
        btnEli = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(222, 222, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar/Eliminar Consulta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("EngraversGothic BT", 0, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(222, 222, 222));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Consulta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("EngraversGothic BT", 0, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));

        txtBus.setBackground(new java.awt.Color(240, 240, 240));
        txtBus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusActionPerformed(evt);
            }
        });
        txtBus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusKeyReleased(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(222, 222, 222));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBus, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(222, 222, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir Solucion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("EngraversGothic BT", 0, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setBackground(new java.awt.Color(222, 222, 222));
        jLabel7.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Codigo de Consulta");

        txtcodcon.setBackground(new java.awt.Color(222, 222, 222));
        txtcodcon.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        txtcodcon.setForeground(new java.awt.Color(0, 0, 0));
        txtcodcon.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(222, 222, 222));
        jLabel1.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre de cliente");

        txtnomcli.setBackground(new java.awt.Color(222, 222, 222));
        txtnomcli.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        txtnomcli.setForeground(new java.awt.Color(0, 0, 0));
        txtnomcli.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(222, 222, 222));
        jLabel2.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre de Tec.");

        txtnomtec.setBackground(new java.awt.Color(222, 222, 222));
        txtnomtec.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        txtnomtec.setForeground(new java.awt.Color(0, 0, 0));
        txtnomtec.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(222, 222, 222));
        jLabel3.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha de Inicio");

        txtfecini.setBackground(new java.awt.Color(222, 222, 222));
        txtfecini.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        txtfecini.setForeground(new java.awt.Color(0, 0, 0));
        txtfecini.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(222, 222, 222));
        jLabel4.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo de problema");

        txtpro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(txtpro);

        jLabel5.setBackground(new java.awt.Color(222, 222, 222));
        jLabel5.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tipo de problema");

        jScrollPane2.setViewportView(txtsol);

        jLabel6.setBackground(new java.awt.Color(222, 222, 222));
        jLabel6.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha de Inicio");

        txtfecter.setBackground(new java.awt.Color(222, 222, 222));
        txtfecter.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        txtfecter.setForeground(new java.awt.Color(0, 0, 0));

        btnAct.setBackground(new java.awt.Color(222, 222, 222));
        btnAct.setFont(new java.awt.Font("EngraversGothic BT", 0, 16)); // NOI18N
        btnAct.setForeground(new java.awt.Color(0, 0, 0));
        btnAct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        btnAct.setText("Actualizar");
        btnAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActActionPerformed(evt);
            }
        });

        txtaptec.setBackground(new java.awt.Color(222, 222, 222));
        txtaptec.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        txtaptec.setForeground(new java.awt.Color(0, 0, 0));
        txtaptec.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel8.setBackground(new java.awt.Color(222, 222, 222));
        jLabel8.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Apellido de Tec.");

        jLabel9.setBackground(new java.awt.Color(222, 222, 222));
        jLabel9.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Apellido de cliente");

        txtapecli.setBackground(new java.awt.Color(222, 222, 222));
        txtapecli.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        txtapecli.setForeground(new java.awt.Color(0, 0, 0));
        txtapecli.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        btnEdi.setBackground(new java.awt.Color(222, 222, 222));
        btnEdi.setFont(new java.awt.Font("EngraversGothic BT", 0, 16)); // NOI18N
        btnEdi.setForeground(new java.awt.Color(0, 0, 0));
        btnEdi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        btnEdi.setText("Editar");
        btnEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdiActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(222, 222, 222));
        jLabel10.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cod Cliente");

        txtcodcli.setBackground(new java.awt.Color(222, 222, 222));
        txtcodcli.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        txtcodcli.setForeground(new java.awt.Color(0, 0, 0));
        txtcodcli.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel11.setBackground(new java.awt.Color(222, 222, 222));
        jLabel11.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Cod Tecnico");

        txtcodtec.setBackground(new java.awt.Color(222, 222, 222));
        txtcodtec.setFont(new java.awt.Font("EngraversGothic BT", 0, 15)); // NOI18N
        txtcodtec.setForeground(new java.awt.Color(0, 0, 0));
        txtcodtec.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        btnEli.setBackground(new java.awt.Color(222, 222, 222));
        btnEli.setFont(new java.awt.Font("EngraversGothic BT", 0, 16)); // NOI18N
        btnEli.setForeground(new java.awt.Color(0, 0, 0));
        btnEli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recycle-full.png"))); // NOI18N
        btnEli.setText("Eliminar");
        btnEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtfecini, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcodcon)
                            .addComponent(txtnomcli, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(65, 65, 65)
                        .addComponent(txtnomtec, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfecter, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtaptec, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcodtec, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtapecli, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btnEdi)
                .addGap(56, 56, 56)
                .addComponent(btnAct, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnEli, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(96, 96, 96)
                        .addComponent(txtcodcli, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtnomcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtapecli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaptec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtnomtec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfecini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtfecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtcodtec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdi)
                    .addComponent(btnAct)
                    .addComponent(btnEli))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusActionPerformed

    private void txtBusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusKeyReleased

    }//GEN-LAST:event_txtBusKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cargar(txtBus.getText());

    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActActionPerformed
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        try {
            PreparedStatement pps = cn.prepareStatement("UPDATE consultas SET cod_con='" + txtcodcon.getText() + "',fec_rev='" + txtfecini.getText() + "',"
                    + "pro_con='" + txtpro.getText() + "',sol_con='" + txtsol.getText() + "',fec_ter='" + txtfecter.getText() + "', cliente_cod_cli='" + txtcodcli.getText() + "',tecnico_cod_tec='" + txtcodtec.getText() + "' WHERE cod_con='" + txtcodcon.getText() + "'");
            pps.executeUpdate();

            JOptionPane.showMessageDialog(null, "datos actualizados");
            limpiar();
            bloquear();

        } catch (SQLException ex) {
            Logger.getLogger(Newtecnico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActActionPerformed

    private void btnEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdiActionPerformed
        desbloquear();
    }//GEN-LAST:event_btnEdiActionPerformed

    private void btnEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliActionPerformed
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        //String nom, ape, tel;
        //int dni;
        String sql = "";
        String cod = txtcodcon.getText();
        //ape = txtape.getText();
        //dni = Integer.parseInt(txtDNI.getText());  //int b = Integer.parseInt("900");  COVERSIOND DE String a Int
        //tel = txtTel.getText();
        sql = "DELETE FROM consultas WHERE cod_con=?";
        try {
            PreparedStatement psd = cn.prepareStatement(sql);
            psd.setString(1, cod);
            int n = psd.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Registro eliminado con exito");
                limpiar();
                bloquear();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAct;
    private javax.swing.JButton btnEdi;
    private javax.swing.JButton btnEli;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtBus;
    private javax.swing.JTextField txtapecli;
    private javax.swing.JTextField txtaptec;
    private javax.swing.JTextField txtcodcli;
    private javax.swing.JTextField txtcodcon;
    private javax.swing.JTextField txtcodtec;
    private javax.swing.JTextField txtfecini;
    private javax.swing.JTextField txtfecter;
    private javax.swing.JTextField txtnomcli;
    private javax.swing.JTextField txtnomtec;
    private javax.swing.JTextPane txtpro;
    private javax.swing.JTextPane txtsol;
    // End of variables declaration//GEN-END:variables
}
